Check for Oort output before continuing to release FYPO.
git-svn-id: svn://svn.code.sf.net/p/pombase/code/phenotype_ontology@350 4fb909f7-64a4-470f-a593-fb4d06049fa2

diff --git a/scripts/release_fypo b/scripts/release_fypo
--- a/scripts/release_fypo
+++ b/scripts/release_fypo
@@ -22,6 +22,8 @@ cd phenotype_ontology
 
 OUT_DIR=`pwd`/oort.tmp
 
+OORT_LOG_FILE=$CURRENT_DIR/ontology-release-runner.log
+
 FYPO_OBO=`pwd`/fypo_edit.obo
 GO_OBO=http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/ontology/editors/gene_ontology_write.obo
 PATO_OBO=http://obo.cvs.sourceforge.net/viewvc/obo/obo/ontology/phenotype/quality.obo
@@ -32,10 +34,16 @@ BRENDA_TISSUE_OBO=http://www.brenda-enzymes.info/ontology/tissue/tree/update/upd
 /usr/local/OBOReleaseManager/scripts/ontology-release-runner -outdir $OUT_DIR \
     --no-subsets -reasoner elk --simple \
     $FYPO_OBO $GO_OBO $PCO_OBO $CHEBI_OBO $CELL_TYPE_OBO $BRENDA_TISSUE_OBO \
-    > $CURRENT_DIR/ontology-release-runner.log 2>&1
+    > $OORT_LOG_FILE 2>&1
 
 release_path=$OUT_DIR/releases/*
 release=`basename $release_path`
+
+if [ -e $release_path ]
+then
+  echo "error: no directories found in $OUT_DIR/releases/ - check $OORT_LOG_FILE" 1>&2
+  exit 1
+fi
 
 new_release_dir=./releases/$release
 svn mkdir $new_release_dir ||
